[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-ads>=26.1.0",
    "phonenumbers>=9.0.5",
    "pyodbc>=5.2.0",
    "pyyaml>=6.0.2",
]
